/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.zxxz_ru;
import com.github.zxxz_ru.command.Dispatcher;
import com.github.zxxz_ru.command.Messenger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Scanner;

@SpringBootApplication
public class App implements CommandLineRunner {
    Dispatcher disp;
    Messenger messenger;
    // InitialDataInserter inserter;

    public static void main(String[] args) {
        try{
        SpringApplication.run(App.class, args);
        } catch (Exception e){
            e.printStackTrace();
        }

    }
    @Autowired
    public App(Dispatcher d/*, InitialDataInserter i*/, Messenger msg){
        this.disp = d;
        this.messenger = msg;
       //  this.inserter = i;
    }
    @Override
    public void run(String... args){
        // inserter.insert();
        disp.dispatch(args);
        while(true) {
            disp.dispatch();
        }
    }
}
