/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.zxxz_ru;
import com.github.zxxz_ru.command.Dispatcher;
import com.github.zxxz_ru.dao.InitialDataInserter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Scanner;

@SpringBootApplication
public class App implements CommandLineRunner {
    Dispatcher disp;
    // InitialDataInserter inserter;

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    @Autowired
    public App(Dispatcher d/*, InitialDataInserter i*/){
        this.disp = d;
       //  this.inserter = i;
    }
    @Override
    public void run(String... args){
        // inserter.insert();
        System.out.println("sjadfdafsdf");
        while(true) {
            Scanner scan = new Scanner(System.in);
            String str = scan.next();
            disp.dispatch(str);
        }
    }
}
